name: Run on workflows
on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ AutoAnime ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
            ref: AutoAnime
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - uses: actions/setup-node@v2
         with:
            node-version: '16'
       - name: Set up Python 3.8.7
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.8.7
       - name: cloning repo and install

         continue-on-error: true
         run: pip3 install -r requirements.txt
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           python3 -m bot
           echo "Bot Died"
